In [110]:
import pandas as pd
import numpy as np
from sklearn.model_selection import LeaveOneOut
from sklearn.linear_model import LogisticRegression
import operator
import matplotlib.pyplot as plt
from openpyxl import load_workbook
import time
from string import ascii_lowercase
import pickle
from scipy.sparse import csr_matrix

df = pd.read_excel("MergedData.xlsx")
df = df.replace({'Male':0}, regex=True)
df = df.replace({'Female':1}, regex=True)
df = df.dropna()

In [158]:
csr_df = csr_matrix(df.drop(["Name"], axis=1))

out = open("MergedData.pkl", "wb")
pickle.dump(csr_df, out)
out.close()

in_df = open("MergedData.pkl", "rb")
now_df = pickle.load(in_df)
in_df.close()
pd.DataFrame(now_df.todense())

       0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16   17
0       0   0   0   0   1   0   0   1   3   0   1   0   5   0   1   0  13  117
1       1   0   1   0   0   0   0   1   3   0   1   1   6   0   1   0   0  624
2       1   0   0   0   0   0   0   2   4   0   0   0   7   0   1   0   7    7
3       1   0   1   0   0   0   0   2   3   0   0   1   5   0   1   0   0  624
4       0   0   0   0   0   1   0   1   3   0   0   0   5   1   1   0  21   21
5       0   0   0   0   0   1   0   1   3   0   0   0   6   1   1   0   7  475
6       0   0   0   1   0   0   0   0   1   0   1   0   2   0   1   0   1    1
7       1   0   0   0   1   0   0   1   4   0   2   0   7   0   1   0  11  219
8       0   0   0   1   0   0   0   0   1   0   2   0   3   0   1   0   1   27
9       1   0   0   0   0   0   0   1   2   0   2   1   5   0   1   0  24  128
10      1   0   0   0   1   0   0   1   4   0   3   0   8   0   1   0  11  219
11      0   0   0   1   0   0   0   0   2   0   4   0   6   0   1   0  19  513
12      1   0   0   0   0   0   0   1   1   0   2   1   4   0   1   0  24   50
13      0   0   0   0   1   0   0   1   3   0   2   0   6   0   1   0  11  115
14      0   0   0   0   1   0   0   1   2   0   2   0   5   0   1   0  11  531
15      0   0   0   0   0   0   0   2   3   0   2   0   8   0   1   0   7    7
16      0   0   0   0   0   0   0   0   2   0   1   1   3   0   1   0   4   30
17      0   0   0   0   1   0   0   1   2   0   1   0   4   0   1   0  11  115
18      0   0   0   0   0   0   0   2   4   0   2   1   8   0   1   0  14   92
19      0   0   0   0   0   0   0   0   3   0   1   1   4   0   1   0   4  212
20      1   0   0   0   1   0   0   1   4   0   2   0   7   0   1   0  11  219
21      1   0   0   0   0   0   0   1   4   0   2   1   7   0   1   0   4  290
22      1   0   0   0   0   0   0   2   4   0   2   1   8   0   1   0   4  290
23      0   0   0   0   1   0   0   2   2   0   1   0   5   0   1   0  17  121
24      0   0   0   0   1   0   0   2   3   0   1   0   7   0   1   0  12   12
25      0   0   0   0   1   0   0   2   2   0   1   0   5   0   1   0  12   12
26      1   0   0   0   0   0   0   3   4   0   1   1   8   0   1   0   4  290
27      1   0   0   0   1   0   0   2   2   0   1   0   5   0   1   0  11  219
28      0   0   0   0   0   0   0   0   2   0   0   1   3   0   1   0   4   56
29      0   0   0   0   0   0   0   1   2   0   0   1   4   0   1   0  24  128
...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...
97072   1   2   1   0   0   0   1   0   3   0   0   1   5   1   0   0   0    0
97073   1   2   1   0   0   0   1   1   4   0   0   1   7   1   0   0   0  442
97074   0   2   0   1   0   0   1   1   2   0   1   0   6   1   0   0   1  625
97075   0   2   0   1   0   0   1   1   2   0   1   0   6   1   0   0   1  625
97076   1   2   0   0   0   1   1   1   2   0   1   0   7   2   0   0   5  525
97077   1   2   1   0   0   0   1   1   4   0   1   1   8   1   0   0   0  182
97078   1   2   1   0   0   0   1   1   5   0   1   1   9   1   0   0   0    0
97079   1   2   0   0   0   0   1   1   4   0   1   0   9   1   0   0   7    7
97080   1   2   1   0   0   0   1   1   3   0   1   1   7   1   0   0   0  182
97081   1   2   0   0   1   0   1   2   2   0   0   0   5   1   0   0  11   11
97082   1   2   1   0   0   0   1   2   3   0   1   1   8   1   0   0   0  182
97083   1   2   1   0   0   0   1   1   4   0   1   1   8   1   0   0   0  182
97084   1   2   1   0   0   0   1   2   3   0   0   1   7   1   0   0   0  182
97085   1   2   1   0   0   0   1   1   2   0   0   1   5   2   0   0   0  130
97086   0   2   0   0   1   0   1   2   3   0   1   0   8   2   0   0  17   17
97087   0   2   0   0   1   0   1   2   3   0   0   0   8   2   0   0  17   17
97088   0   2   0   0   1   0   1   4   4   0   1   0  10   1   0   0  13  221
97089   0   2   0   0   1   0   1   4   4   0   0   0  10   1   0   0  13  221
97090   0   2   0   1   0   0   1   1   3   0   1   0   6   1   0   0   3  211
97091   0   2   0   0   1   0   1   2   3   0   0   0   6   1   0   0  17  225
97092   1   2   0   0   0   0   1   3   3   0   0   0   8   1   0   0   7    7
97093   1   2   0   0   0   1   1   1   2   0   1   0   6   2   0   0  18  538
97094   1   2   1   0   0   0   1   2   3   0   0   1   6   1   0   0   0  442
97095   0   2   0   0   0   0   1   1   3   0   1   1   6   1   0   0   8   34
97096   1   2   1   0   0   0   1   0   2   0   0   1   4   2   0   0   0  546
97097   1   2   1   0   0   0   1   0   3   0   0   1   5   2   0   0   0  208
97098   1   2   0   0   0   0   1   3   5   0   2   1  12   2   0   0  14  456
97099   0   2   0   0   0   0   1   3   3   0   0   1   8   1   0   0   4  290
97100   0   2   0   0   0   1   1   3   3   0   2   0  10   2   0   0  18   18
97101   1   2   1   0   0   0   1   1   1   0   0   1   4   2   0   0   0  546

[97102 rows x 18 columns]

In [159]:
df

,Name,Gender,dataID,A ending?,"Plosive ending? (p,b,t,d,k,g)","Sonorant ending? (m,n,ng,l,r)","Fricative ending? (f,v,th,s,z,sh,ch,dge)","1st letter fricative? (f,v,th,s,z,sh,ch,j)","Total # of sonorants (m,n,l,r,w,y)","Total # of vowels (a, e, i, o, u)","1st letter plosive? (p,b,t,d,k,g)","Total # of plosives (p,b,t,d,k,g)","VowelEnding? (a, e, i, o, u,y)",# of letters,"# of fricatives (f,v,th,s,z,sh,ch,j)","1st letter vowel? (a, e, i, o, u)","1st letter sonorant? (m,n,l,r,w,y)",Last Letter,Last Two
0,aaden,0,0,0,0,1,0,0,1,3,0,1,0,5,0,1,0,13,117
1,aadhya,1,0,1,0,0,0,0,1,3,0,1,1,6,0,1,0,0,624
2,aaliyah,1,0,0,0,0,0,0,2,4,0,0,0,7,0,1,0,7,7
3,aanya,1,0,1,0,0,0,0,2,3,0,0,1,5,0,1,0,0,624
4,aarav,0,0,0,0,0,1,0,1,3,0,0,0,5,1,1,0,21,21
5,aarush,0,0,0,0,0,1,0,1,3,0,0,0,6,1,1,0,7,475
6,ab,0,0,0,1,0,0,0,0,1,0,1,0,2,0,1,0,1,1
7,abagail,1,0,0,0,1,0,0,1,4,0,2,0,7,0,1,0,11,219
8,abb,0,0,0,1,0,0,0,0,1,0,2,0,3,0,1,0,1,27
9,abbey,1,0,0,0,0,0,0,1,2,0,2,1,5,0,1,0,24,128
10,abbigail,1,0,0,0,1,0,0,1,4,0,3,0,8,0,1,0,11,219
11,abbott,0,0,0,1,0,0,0,0,2,0,4,0,6,0,1,0,19,513
12,abby,1,0,0,0,0,0,0,1,1,0,2,1,4,0,1,0,24,50
13,abdiel,0,0,0,0,1,0,0,1,3,0,2,0,6,0,1,0,11,115
14,abdul,0,0,0,0,1,0,0,1,2,0,2,0,5,0,1,0,11,531
15,abdullah,0,0,0,0,0,0,0,2,3,0,2,0,8,0,1,0,7,7
16,abe,0,0,0,0,0,0,0,0,2,0,1,1,3,0,1,0,4,30
17,abel,0,0,0,0,1,0,0,1,2,0,1,0,4,0,1,0,11,115
18,abelardo,0,0,0,0,0,0,0,2,4,0,2,1,8,0,1,0,14,92
19,abie,0,0,0,0,0,0,0,0,3,0,1,1,4,0,1,0,4,212
20,abigail,1,0,0,0,1,0,0,1,4,0,2,0,7,0,1,0,11,219
21,abigale,1,0,0,0,0,0,0,1,4,0,2,1,7,0,1,0,4,290
22,abigayle,1,0,0,0,0,0,0,2,4,0,2,1,8,0,1,0,4,290
23,abner,0,0,0,0,1,0,0,2,2,0,1,0,5,0,1,0,17,121
24,abraham,0,0,0,0,1,0,0,2,3,0,1,0,7,0,1,0,12,12
25,abram,0,0,0,0,1,0,0,2,2,0,1,0,5,0,1,0,12,12
26,abrielle,1,0,0,0,0,0,0,3,4,0,1,1,8,0,1,0,4,290
27,abril,1,0,0,0,1,0,0,2,2,0,1,0,5,0,1,0,11,219
28,ace,0,0,0,0,0,0,0,0,2,0,0,1,3,0,1,0,4,56
29,acey,0,0,0,0,0,0,0,1,2,0,0,1,4,0,1,0,24,128
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97072,zuhaa,1,2,1,0,0,0,1,0,3,0,0,1,5,1,0,0,0,0
97073,zuhaira,1,2,1,0,0,0,1,1,4,0,0,1,7,1,0,0,0,442
97074,zuhayb,0,2,0,1,0,0,1,1,2,0,1,0,6,1,0,0,1,625
97075,zuheyb,0,2,0,1,0,0,1,1,2,0,1,0,6,1,0,0,1,625
97076,zukhruf,1,2,0,0,0,1,1,1,2,0,1,0,7,2,0,0,5,525
97077,zulaikha,1,2,1,0,0,0,1,1,4,0,1,1,8,1,0,0,0,182
97078,zulaikhaa,1,2,1,0,0,0,1,1,5,0,1,1,9,1,0,0,0,0
97079,zulaikhah,1,2,0,0,0,0,1,1,4,0,1,0,9,1,0,0,7,7
97080,zulakha,1,2,1,0,0,0,1,1,3,0,1,1,7,1,0,0,0,182
97081,zulal,1,2,0,0,1,0,1,2,2,0,0,0,5,1,0,0,11,11
97082,zulaykha,1,2,1,0,0,0,1,2,3,0,1,1,8,1,0,0,0,182
97083,zuleikha,1,2,1,0,0,0,1,1,4,0,1,1,8,1,0,0,0,182
97084,zuleyha,1,2,1,0,0,0,1,2,3,0,0,1,7,1,0,0,0,182
97085,zulfa,1,2,1,0,0,0,1,1,2,0,0,1,5,2,0,0,0,130
97086,zulfikar,0,2,0,0,1,0,1,2,3,0,1,0,8,2,0,0,17,17
97087,zulfiqar,0,2,0,0,1,0,1,2,3,0,0,0,8,2,0,0,17,17
97088,zulkarnain,0,2,0,0,1,0,1,4,4,0,1,0,10,1,0,0,13,221
97089,zulqarnain,0,2,0,0,1,0,1,4,4,0,0,0,10,1,0,0,13,221
97090,zunaid,0,2,0,1,0,0,1,1,3,0,1,0,6,1,0,0,3,211
97091,zunair,0,2,0,0,1,0,1,2,3,0,0,0,6,1,0,0,17,225
97092,zunayrah,1,2,0,0,0,0,1,3,3,0,0,0,8,1,0,0,7,7
97093,zundus,1,2,0,0,0,1,1,1,2,0,1,0,6,2,0,0,18,538
97094,zunera,1,2,1,0,0,0,1,2,3,0,0,1,6,1,0,0,0,442
97095,zurabi,0,2,0,0,0,0,1,1,3,0,1,1,6,1,0,0,8,34
97096,zuva,1,2,1,0,0,0,1,0,2,0,0,1,4,2,0,0,0,546
97097,zuzia,1,2,1,0,0,0,1,0,3,0,0,1,5,2,0,0,0,208
97098,zvikomborero,1,2,0,0,0,0,1,3,5,0,2,1,12,2,0,0,14,456
97099,zwelihle,0,2,0,0,0,0,1,3,3,0,0,1,8,1,0,0,4,290
97100,zygimantas,0,2,0,0,0,1,1,3,3,0,2,0,10,2,0,0,18,18
97101,zyva,1,2,1,0,0,0,1,1,1,0,0,1,4,2,0,0,0,546

In [29]:
dfLetters = df[['Name', 'Gender']]

for c1 in ascii_lowercase:
    print(c1)
    dfLetters.insert(len(dfLetters.columns), "Starts with: " + c1, 0)
    dfLetters.loc[(dfLetters['Name'].str.startswith(c1)), "Starts with: " + c1] = 1
    
    dfLetters.insert(len(dfLetters.columns), "Ends with: " + c1, 0)
    dfLetters.loc[(dfLetters['Name'].str.endswith(c1)), "Ends with: " + c1] = 1
    
    for c2 in ascii_lowercase:
        dfLetters.insert(len(dfLetters.columns), "Starts with: " + c1 + c2, 0)
        dfLetters.loc[(dfLetters['Name'].str.startswith(c1 + c2)), "Starts with: " + c1 + c2] = 1

        dfLetters.insert(len(dfLetters.columns), "Ends with: " + c1 + c2, 0)
        dfLetters.loc[(dfLetters['Name'].str.endswith(c1 + c2)), "Ends with: " + c1 + c2] = 1
        
        file = open("merged_3_letter.pkl", "wb")
        pickle.dump(dfLetters, file)
        file.close()
        
        for c3 in ascii_lowercase:
            dfLetters.insert(len(dfLetters.columns), "Starts with: " + c1 + c2 + c3, 0)
            dfLetters.loc[(dfLetters['Name'].str.startswith(c1 + c2 + c3)), "Starts with: " + c1 + c2 + c3] = 1

            dfLetters.insert(len(dfLetters.columns), "Ends with: " + c1 + c2 + c3, 0)
            dfLetters.loc[(dfLetters['Name'].str.endswith(c1 + c2 + c3)), "Ends with: " + c1 + c2 + c3] = 1

a

C:\Users\Samin\Anaconda3\lib\site-packages\pandas\core\indexing.py:477: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

b
c
d

KeyboardInterrupt:

In [36]:
from sklearn.model_selection import KFold

"""LOOCV ANALYSIS"""
# Change parameter depending on target feature
dfLooTest = dfLetters

# Timing LOOCV runtime
t0 = time.time()
    
# Uses Leave One Out Cross Validation (LOOCV) to estimate how training model would do on predicting external data
loo = KFold(n_splits=10)
x = dfLooTest.drop(['gender'], axis=1).as_matrix()
y = dfLooTest[['gender']].as_matrix().ravel()

male_total = 0
correct_male = 0
female_total = 0
correct_female = 0

errNames = [('gender', 'Name')]

# Can optionally recreate a model to exclude the last training round
model = LogisticRegression(C=1e5)

for train_index, test_index in loo.split(x):
    x_train, x_test = x[train_index], x[test_index]
    y_train, y_test = y[train_index], y[test_index]
    model.fit(x_train, y_train)
    prediction = model.predict(x_test)
    
    if y_test == [0]:
        male_total += 1
        correct_male += 1 if prediction == y_test else 0
    else:
        female_total += 1
        correct_female += 1 if prediction == y_test else 0
    if y_test != prediction:
        errNames.append(('y_test', dfLetters.Name[test_index]))
overallAcc = (correct_male + correct_female) / (male_total + female_total)
maleAcc = correct_male / male_total
femaleAcc = correct_female / female_total

t1 = time.time()
runtime = t1 - t0

coefficients = {}
for i in range(len(dfLooTest.columns) - 1):
    coefficients[dfLooTest.columns[i + 1]] = model.coef_[0][i]

sorted_x = sorted(coefficients.items(), key=operator.itemgetter(1), reverse=True)
print(dfLooTest.columns)
print("Runtime: " + str(runtime))
print("Overall accuracy: " + str(overallAcc))
print("Male accuracy: " + str(maleAcc))
print("Female accuracy: " + str(femaleAcc))
print("\nCoefficients: \n")
print({'Total male': male_total, 'Correct male': correct_male, 'Total female': female_total, 'Correct female': correct_female})


dfCoefficients = pd.DataFrame(sorted_x)
excel_dir = '3-letterAnalyses.xlsx'
book = load_workbook(excel_dir)
with pd.ExcelWriter(excel_dir, engine='openpyxl') as writer:
    writer.book = book
    writer.sheets = dict((ws.title, ws) for ws in book.worksheets)    
    ## Your dataframe to append. 
    dfCoefficients.to_excel(writer, 'Sheet1', index=False)
    writer.save()  
writer.close()

dfWrongNames = pd.DataFrame(errNames)
book = load_workbook(excel_dir)
with pd.ExcelWriter(excel_dir, engine='openpyxl') as writer:
    writer.book = book
    writer.sheets = dict((ws.title, ws) for ws in book.worksheets)    
    ## Your dataframe to append. 
    dfCoefficients.to_excel(writer, 'Sheet2', index=False)
    writer.save()  
writer.close()

C:\Users\Samin\Anaconda3\lib\site-packages\pandas\core\generic.py:2773: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value

               Name  Gender
0             aaden       0
1            aadhya       1
2           aaliyah       1
3             aanya       1
4             aarav       0
5            aarush       0
6                ab       0
7           abagail       1
8               abb       0
9             abbey       1
10         abbigail       1
11           abbott       0
12             abby       1
13           abdiel       0
14            abdul       0
15         abdullah       0
16              abe       0
17             abel       0
18         abelardo       0
19             abie       0
20          abigail       1
21          abigale       1
22         abigayle       1
23            abner       0
24          abraham       0
25            abram       0
26         abrielle       1
27            abril       1
28              ace       0
29             acey       0
...             ...     ...
97072         zuhaa       1
97073       zuhaira       1
97074        zuhayb       0
97075        zuheyb       0
97076       zukhruf       1
97077      zulaikha       1
97078     zulaikhaa       1
97079     zulaikhah       1
97080       zulakha       1
97081         zulal       1
97082      zulaykha       1
97083      zuleikha       1
97084       zuleyha       1
97085         zulfa       1
97086      zulfikar       0
97087      zulfiqar       0
97088    zulkarnain       0
97089    zulqarnain       0
97090        zunaid       0
97091        zunair       0
97092      zunayrah       1
97093        zundus       1
97094        zunera       1
97095        zurabi       0
97096          zuva       1
97097         zuzia       1
97098  zvikomborero       1
97099      zwelihle       0
97100    zygimantas       0
97101          zyva       1

[97102 rows x 2 columns]

In [42]:
dfBare.Name[2]

'aaliyah'